import item1 from "../../../itemImg/item1.jpg";
export const list = [
  {
    id: "SP01",
    tenSanPham: "Sản phẩm 1",
    maTheLoai: "Loại 01",
    hinhAnh: item1,
    giaBan: "100000đ",
    nhaCungCap: "NCC 01",
    xuatXu: "Việt Nam",
    trongLuong: "0.2kg",
    kichCo: "XL",
    mauSac: "Đỏ",
  },
  {
    id: "SP01",
    tenSanPham: "Sản phẩm 1",
    maTheLoai: "Loại 01",
    hinhAnh: item1,
    giaBan: "100000đ",
    nhaCungCap: "NCC 01",
    xuatXu: "Việt Nam",
    trongLuong: "0.2kg",
    kichCo: "XL",
    mauSac: "Đỏ",
  },
  {
    id: "SP01",
    tenSanPham: "Sản phẩm 1",
    maTheLoai: "Loại 01",
    hinhAnh: item1,
    giaBan: "100000đ",
    nhaCungCap: "NCC 01",
    xuatXu: "Việt Nam",
    trongLuong: "0.2kg",
    kichCo: "XL",
    mauSac: "Đỏ",
  },
  {
    id: "SP01",
    tenSanPham: "Sản phẩm 1",
    maTheLoai: "Loại 01",
    hinhAnh: item1,
    giaBan: "100000đ",
    nhaCungCap: "NCC 01",
    xuatXu: "Việt Nam",
    trongLuong: "0.2kg",
    kichCo: "XL",
    mauSac: "Đỏ",
  },
  {
    id: "SP01",
    tenSanPham: "Sản phẩm 1",
    maTheLoai: "Loại 01",
    hinhAnh: item1,
    giaBan: "100000đ",
    nhaCungCap: "NCC 01",
    xuatXu: "Việt Nam",
    trongLuong: "0.2kg",
    kichCo: "XL",
    mauSac: "Đỏ",
  },
  {
    id: "SP01",
    tenSanPham: "Sản phẩm 1",
    maTheLoai: "Loại 01",
    hinhAnh: item1,
    giaBan: "100000đ",
    nhaCungCap: "NCC 01",
    xuatXu: "Việt Nam",
    trongLuong: "0.2kg",
    kichCo: "XL",
    mauSac: "Đỏ",
  },
  {
    id: "SP01",
    tenSanPham: "Sản phẩm 1",
    maTheLoai: "Loại 01",
    hinhAnh: item1,
    giaBan: "100000đ",
    nhaCungCap: "NCC 01",
    xuatXu: "Việt Nam",
    trongLuong: "0.2kg",
    kichCo: "XL",
    mauSac: "Đỏ",
  },
  {
    id: "SP01",
    tenSanPham: "Sản phẩm 1",
    maTheLoai: "Loại 01",
    hinhAnh: item1,
    giaBan: "100000đ",
    nhaCungCap: "NCC 01",
    xuatXu: "Việt Nam",
    trongLuong: "0.2kg",
    kichCo: "XL",
    mauSac: "Đỏ",
  },
  {
    id: "SP01",
    tenSanPham: "Sản phẩm 1",
    maTheLoai: "Loại 01",
    hinhAnh: item1,
    giaBan: "100000đ",
    nhaCungCap: "NCC 01",
    xuatXu: "Việt Nam",
    trongLuong: "0.2kg",
    kichCo: "XL",
    mauSac: "Đỏ",
  },
  {
    id: "SP01",
    tenSanPham: "Sản phẩm 1",
    maTheLoai: "Loại 01",
    hinhAnh: item1,
    giaBan: "100000đ",
    nhaCungCap: "NCC 01",
    xuatXu: "Việt Nam",
    trongLuong: "0.2kg",
    kichCo: "XL",
    mauSac: "Đỏ",
  },
  {
    id: "SP01",
    tenSanPham: "Sản phẩm 1",
    maTheLoai: "Loại 01",
    hinhAnh: item1,
    giaBan: "100000đ",
    nhaCungCap: "NCC 01",
    xuatXu: "Việt Nam",
    trongLuong: "0.2kg",
    kichCo: "XL",
    mauSac: "Đỏ",
  },
  {
    id: "SP01",
    tenSanPham: "Sản phẩm 1",
    maTheLoai: "Loại 01",
    hinhAnh: item1,
    giaBan: "100000đ",
    nhaCungCap: "NCC 01",
    xuatXu: "Việt Nam",
    trongLuong: "0.2kg",
    kichCo: "XL",
    mauSac: "Đỏ",
  },
  {
    id: "SP01",
    tenSanPham: "Sản phẩm 1",
    maTheLoai: "Loại 01",
    hinhAnh: item1,
    giaBan: "100000đ",
    nhaCungCap: "NCC 01",
    xuatXu: "Việt Nam",
    trongLuong: "0.2kg",
    kichCo: "XL",
    mauSac: "Đỏ",
  },
];
