import item1 from "./itemImg/item1.jpg";
export const listItem = [
    {
        ID: "SP01",
        name: "name1",
        src: item1,
        price: 100000,
        type: "newItem",
    },
    {
        ID: "SP01",
        name: "name1",
        src: item1,
        price: 100000,
        type: "newItem",
    },
    {
        ID: "SP01",
        name: "name1",
        src: item1,
        price: 100000,
        type: "newItem",
    },
    {
        ID: "SP01",
        name: "name1",
        src: item1,
        price: 100000,
        type: "newItem",
    },
    {
        ID: "SP01",
        name: "name1",
        src: item1,
        price: 100000,
        type: "newItem",
    },
    {
        ID: "SP02",
        name: "name2",
        src: item1,
        price: 100000,
        type: "CLB",
    },
    {
        ID: "SP03",
        name: "name3",
        src: item1,
        price: 100000,
        type: "newItem",
    },
    {
        ID: "SP04",
        name: "name4",
        src: item1,
        price: 100000,
        type: "newItem",
    },
    {
        ID: "SP05",
        name: "name5",
        src: item1,
        price: 100000,
        type: "CLB",
    },
    {
        ID: "SP06",
        name: "name6",
        src: item1,
        price: 100000,
        type: "CLB",
    },
    {
        ID: "SP07",
        name: "name7",
        src: item1,
        price: 100000,
        type: "CLB",
    },
    {
        ID: "SP08",
        name: "name8",
        src: item1,
        price: 100000,
        type: "Kid",
    }
]