import item1 from "./itemImg/item1.jpg";
import TypeItem from "./const/typeItem";
export const listItem = [
  {
    ID: "SP01",
    name: "name1",
    src: item1,
    price: 100000,
    type: TypeItem.NEW_ITEM,
  },
  {
    ID: "SP01",
    name: "name1",
    src: item1,
    price: 100000,
    type: TypeItem.NEW_ITEM,
  },
  {
    ID: "SP01",
    name: "name1",
    src: item1,
    price: 100000,
    type: TypeItem.NEW_ITEM,
  },
  {
    ID: "SP01",
    name: "name1",
    src: item1,
    price: 100000,
    type: TypeItem.NEW_ITEM,
  },
  {
    ID: "SP01",
    name: "name1",
    src: item1,
    price: 100000,
    type: TypeItem.NEW_ITEM,
  },
  {
    ID: "SP02",
    name: "name2",
    src: item1,
    price: 100000,
    type: TypeItem.CLB,
  },
  {
    ID: "SP03",
    name: "name3",
    src: item1,
    price: 100000,
    type: TypeItem.NEW_ITEM,
  },
  {
    ID: "SP04",
    name: "name4",
    src: item1,
    price: 100000,
    type: TypeItem.NEW_ITEM,
  },
  {
    ID: "SP06",
    name: "name6",
    src: item1,
    price: 1000000,
    type: TypeItem.CLB,
  },
  {
    ID: "SP07",
    name: "name7",
    src: item1,
    price: 100000,
    type: TypeItem.CLB,
  },
  {
    ID: "SP08",
    name: "name8",
    src: item1,
    price: 100000,
    type: TypeItem.KID,
  },
];
